apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  type: NodePort
  ports:
    - port: 32768
      nodePort: 30001
      targetPort: 50001
  selector:
    app: user