// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/book/create": {
            "post": {
                "description": "新增图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "新增图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "create book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.CreateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.CreateBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.CreateBookResponse"
                        }
                    }
                }
            }
        },
        "/admin/book/delete/{book_id}": {
            "delete": {
                "description": "删除图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "删除图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "delete book id",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteBookResponse"
                        }
                    }
                }
            }
        },
        "/admin/book/record/all": {
            "post": {
                "description": "所有用户所有借阅图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "所有用户所有借阅图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list all book records request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBookRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBookRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBookRecordsResponse"
                        }
                    }
                }
            }
        },
        "/admin/book/record/borrow": {
            "post": {
                "description": "所有用户待还图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "所有用户待还图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list all borrowed book records request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBorrowedBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBorrowedBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllBorrowedBookResponse"
                        }
                    }
                }
            }
        },
        "/admin/book/record/return": {
            "post": {
                "description": "所有用户已还图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "所有用户已还图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list all returned book records request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllReturnedBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllReturnedBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllReturnedBookResponse"
                        }
                    }
                }
            }
        },
        "/admin/book/update": {
            "post": {
                "description": "更改图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "更改图书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateBookResponse"
                        }
                    }
                }
            }
        },
        "/admin/user/delete/{user_id}": {
            "delete": {
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "delete user id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserResponse"
                        }
                    }
                }
            }
        },
        "/admin/user/list": {
            "post": {
                "description": "所有用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取所有用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list all user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllUsersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListAllUsersResponse"
                        }
                    }
                }
            }
        },
        "/book/borrow": {
            "post": {
                "description": "借阅图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "借阅图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "borrow book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.BorrowBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.BorrowBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.BorrowBookResponse"
                        }
                    }
                }
            }
        },
        "/book/list": {
            "post": {
                "description": "分页图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "图书列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListBooksRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBooksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBooksResponse"
                        }
                    }
                }
            }
        },
        "/book/record/all": {
            "post": {
                "description": "所有借阅图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "所有借阅图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list book records request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListBookRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBookRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBookRecordsResponse"
                        }
                    }
                }
            }
        },
        "/book/record/borrow": {
            "post": {
                "description": "待还图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "待还图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list borrowed book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListBorrowedBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBorrowedBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListBorrowedBookResponse"
                        }
                    }
                }
            }
        },
        "/book/record/return": {
            "post": {
                "description": "已还图书记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "已还图书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "list returned book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ListReturnedBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ListReturnedBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ListReturnedBookResponse"
                        }
                    }
                }
            }
        },
        "/book/return": {
            "post": {
                "description": "归还图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "归还图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "return book request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ReturnBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.ReturnBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.ReturnBookResponse"
                        }
                    }
                }
            }
        },
        "/token/admin": {
            "get": {
                "description": "生成管理员token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "temp"
                ],
                "summary": "生成管理员token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/token/user": {
            "get": {
                "description": "生成用户token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "temp"
                ],
                "summary": "生成用户token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "description": "用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    }
                }
            }
        },
        "/user/info/update": {
            "post": {
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "update user info request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateUserInfoRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.UpdateUserInfoResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.LoginResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contract.BaseResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_info": {
                    "$ref": "#/definitions/contract.StatusInfo"
                }
            }
        },
        "contract.BorrowBookRequest": {
            "type": "object",
            "required": [
                "book_id"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                }
            }
        },
        "contract.BorrowBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.CreateBookRequest": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/entity.Book"
                }
            }
        },
        "contract.CreateBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.DeleteBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.DeleteUserResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.GetUserInfoResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "user": {
                    "$ref": "#/definitions/entity.User"
                }
            }
        },
        "contract.ListAllBookRecordsRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListAllBookRecordsResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.ListAllBorrowedBookRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListAllBorrowedBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.ListAllReturnedBookRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListAllReturnedBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.ListAllUsersRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListAllUsersResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.User"
                    }
                }
            }
        },
        "contract.ListBookRecordsRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListBookRecordsResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.ListBooksRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListBooksResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "books": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Book"
                    }
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                }
            }
        },
        "contract.ListBorrowedBookRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListBorrowedBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.ListReturnedBookRequest": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "contract.ListReturnedBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "page_info": {
                    "$ref": "#/definitions/entity.PageInfo"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Record"
                    }
                }
            }
        },
        "contract.LoginRequest": {
            "type": "object",
            "required": [
                "user_auth"
            ],
            "properties": {
                "user_auth": {
                    "$ref": "#/definitions/entity.UserAuth"
                }
            }
        },
        "contract.LoginResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                },
                "user_info": {
                    "$ref": "#/definitions/entity.User"
                }
            }
        },
        "contract.RegisterRequest": {
            "type": "object",
            "required": [
                "user_auth"
            ],
            "properties": {
                "user_auth": {
                    "$ref": "#/definitions/entity.UserAuth"
                }
            }
        },
        "contract.RegisterResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.ReturnBookRequest": {
            "type": "object",
            "required": [
                "book_id"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                }
            }
        },
        "contract.ReturnBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.StatusInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "contract.UpdateBookRequest": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/entity.Book"
                }
            }
        },
        "contract.UpdateBookResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "contract.UpdateUserInfoRequest": {
            "type": "object",
            "required": [
                "user"
            ],
            "properties": {
                "user": {
                    "$ref": "#/definitions/entity.User"
                }
            }
        },
        "contract.UpdateUserInfoResponse": {
            "type": "object",
            "properties": {
                "base_response": {
                    "$ref": "#/definitions/contract.BaseResponse"
                }
            }
        },
        "entity.Book": {
            "type": "object",
            "required": [
                "author",
                "book_name",
                "isbn",
                "publisher"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "book_id": {
                    "type": "integer"
                },
                "book_name": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "img_url": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string"
                },
                "publisher": {
                    "type": "string"
                },
                "rent_status": {
                    "description": "1：未借出 2：已借出",
                    "type": "integer"
                }
            }
        },
        "entity.PageInfo": {
            "type": "object",
            "properties": {
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "entity.Record": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/entity.Book"
                },
                "status": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "required": [
                "name",
                "user_id"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.UserAuth": {
            "type": "object",
            "required": [
                "password",
                "user_id"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
