// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bookpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	GetAllBooks(ctx context.Context, in *GetAllBooksRequest, opts ...grpc.CallOption) (*GetAllBooksResponse, error)
	GetBooksByPage(ctx context.Context, in *GetBooksByPageRequest, opts ...grpc.CallOption) (*GetBooksByPageResponse, error)
	GetBookById(ctx context.Context, in *GetBookByIdRequest, opts ...grpc.CallOption) (*GetBookByIdResponse, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error)
	DeleteBookById(ctx context.Context, in *DeleteBookByIdRequest, opts ...grpc.CallOption) (*DeleteBookByIdResponse, error)
	CheckBookBorrowed(ctx context.Context, in *CheckBookBorrowedRequest, opts ...grpc.CallOption) (*CheckBookBorrowedResponse, error)
	SetBookBorrowed(ctx context.Context, in *SetBookBorrowedRequest, opts ...grpc.CallOption) (*SetBookBorrowedResponse, error)
	SetBookReturned(ctx context.Context, in *SetBookReturnedRequest, opts ...grpc.CallOption) (*SetBookReturnedResponse, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetAllBooks(ctx context.Context, in *GetAllBooksRequest, opts ...grpc.CallOption) (*GetAllBooksResponse, error) {
	out := new(GetAllBooksResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/GetAllBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBooksByPage(ctx context.Context, in *GetBooksByPageRequest, opts ...grpc.CallOption) (*GetBooksByPageResponse, error) {
	out := new(GetBooksByPageResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/GetBooksByPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBookById(ctx context.Context, in *GetBookByIdRequest, opts ...grpc.CallOption) (*GetBookByIdResponse, error) {
	out := new(GetBookByIdResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/GetBookById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error) {
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error) {
	out := new(UpdateBookResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBookById(ctx context.Context, in *DeleteBookByIdRequest, opts ...grpc.CallOption) (*DeleteBookByIdResponse, error) {
	out := new(DeleteBookByIdResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/DeleteBookById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CheckBookBorrowed(ctx context.Context, in *CheckBookBorrowedRequest, opts ...grpc.CallOption) (*CheckBookBorrowedResponse, error) {
	out := new(CheckBookBorrowedResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/CheckBookBorrowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SetBookBorrowed(ctx context.Context, in *SetBookBorrowedRequest, opts ...grpc.CallOption) (*SetBookBorrowedResponse, error) {
	out := new(SetBookBorrowedResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/SetBookBorrowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SetBookReturned(ctx context.Context, in *SetBookReturnedRequest, opts ...grpc.CallOption) (*SetBookReturnedResponse, error) {
	out := new(SetBookReturnedResponse)
	err := c.cc.Invoke(ctx, "/sdk.BookService/SetBookReturned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	GetAllBooks(context.Context, *GetAllBooksRequest) (*GetAllBooksResponse, error)
	GetBooksByPage(context.Context, *GetBooksByPageRequest) (*GetBooksByPageResponse, error)
	GetBookById(context.Context, *GetBookByIdRequest) (*GetBookByIdResponse, error)
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*UpdateBookResponse, error)
	DeleteBookById(context.Context, *DeleteBookByIdRequest) (*DeleteBookByIdResponse, error)
	CheckBookBorrowed(context.Context, *CheckBookBorrowedRequest) (*CheckBookBorrowedResponse, error)
	SetBookBorrowed(context.Context, *SetBookBorrowedRequest) (*SetBookBorrowedResponse, error)
	SetBookReturned(context.Context, *SetBookReturnedRequest) (*SetBookReturnedResponse, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) GetAllBooks(context.Context, *GetAllBooksRequest) (*GetAllBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBooks not implemented")
}
func (UnimplementedBookServiceServer) GetBooksByPage(context.Context, *GetBooksByPageRequest) (*GetBooksByPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooksByPage not implemented")
}
func (UnimplementedBookServiceServer) GetBookById(context.Context, *GetBookByIdRequest) (*GetBookByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookById not implemented")
}
func (UnimplementedBookServiceServer) CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) UpdateBook(context.Context, *UpdateBookRequest) (*UpdateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookServiceServer) DeleteBookById(context.Context, *DeleteBookByIdRequest) (*DeleteBookByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookById not implemented")
}
func (UnimplementedBookServiceServer) CheckBookBorrowed(context.Context, *CheckBookBorrowedRequest) (*CheckBookBorrowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBookBorrowed not implemented")
}
func (UnimplementedBookServiceServer) SetBookBorrowed(context.Context, *SetBookBorrowedRequest) (*SetBookBorrowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBookBorrowed not implemented")
}
func (UnimplementedBookServiceServer) SetBookReturned(context.Context, *SetBookReturnedRequest) (*SetBookReturnedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBookReturned not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_GetAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/GetAllBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetAllBooks(ctx, req.(*GetAllBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBooksByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBooksByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/GetBooksByPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBooksByPage(ctx, req.(*GetBooksByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBookById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBookById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/GetBookById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBookById(ctx, req.(*GetBookByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBookById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBookById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/DeleteBookById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBookById(ctx, req.(*DeleteBookByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CheckBookBorrowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBookBorrowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CheckBookBorrowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/CheckBookBorrowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CheckBookBorrowed(ctx, req.(*CheckBookBorrowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_SetBookBorrowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBookBorrowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).SetBookBorrowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/SetBookBorrowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).SetBookBorrowed(ctx, req.(*SetBookBorrowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_SetBookReturned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBookReturnedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).SetBookReturned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.BookService/SetBookReturned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).SetBookReturned(ctx, req.(*SetBookReturnedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllBooks",
			Handler:    _BookService_GetAllBooks_Handler,
		},
		{
			MethodName: "GetBooksByPage",
			Handler:    _BookService_GetBooksByPage_Handler,
		},
		{
			MethodName: "GetBookById",
			Handler:    _BookService_GetBookById_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBookById",
			Handler:    _BookService_DeleteBookById_Handler,
		},
		{
			MethodName: "CheckBookBorrowed",
			Handler:    _BookService_CheckBookBorrowed_Handler,
		},
		{
			MethodName: "SetBookBorrowed",
			Handler:    _BookService_SetBookBorrowed_Handler,
		},
		{
			MethodName: "SetBookReturned",
			Handler:    _BookService_SetBookReturned_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookpb/service.proto",
}
